import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/toaster";
import { RadioValuesProvider } from "./components/RadioValues";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Health AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={inter.className}>
        <RadioValuesProvider>

          <StoreProvider>
            <Navbar />
            {children}
          </StoreProvider>
          <Toaster />
        </RadioValuesProvider>
      </body>
    </html>
  );
}
